// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: pkg/api/liviva.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ClientMessage_Text
	//	*ClientMessage_AudioChunk
	//	*ClientMessage_SystemCommand
	Payload       isClientMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	mi := &file_pkg_api_liviva_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_liviva_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_pkg_api_liviva_proto_rawDescGZIP(), []int{0}
}

func (x *ClientMessage) GetPayload() isClientMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ClientMessage) GetText() string {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_Text); ok {
			return x.Text
		}
	}
	return ""
}

func (x *ClientMessage) GetAudioChunk() []byte {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_AudioChunk); ok {
			return x.AudioChunk
		}
	}
	return nil
}

func (x *ClientMessage) GetSystemCommand() string {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_SystemCommand); ok {
			return x.SystemCommand
		}
	}
	return ""
}

type isClientMessage_Payload interface {
	isClientMessage_Payload()
}

type ClientMessage_Text struct {
	Text string `protobuf:"bytes,1,opt,name=text,proto3,oneof"` // User typed text or transcribed speech
}

type ClientMessage_AudioChunk struct {
	AudioChunk []byte `protobuf:"bytes,2,opt,name=audio_chunk,json=audioChunk,proto3,oneof"` // Raw audio bytes (PCM) from microphone
}

type ClientMessage_SystemCommand struct {
	SystemCommand string `protobuf:"bytes,3,opt,name=system_command,json=systemCommand,proto3,oneof"` // e.g. "/voice on", "/shutdown"
}

func (*ClientMessage_Text) isClientMessage_Payload() {}

func (*ClientMessage_AudioChunk) isClientMessage_Payload() {}

func (*ClientMessage_SystemCommand) isClientMessage_Payload() {}

type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerMessage_Text
	//	*ServerMessage_AudioChunk
	//	*ServerMessage_ToolCall
	//	*ServerMessage_SystemLog
	//	*ServerMessage_SpeakText
	Payload       isServerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_pkg_api_liviva_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_liviva_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_pkg_api_liviva_proto_rawDescGZIP(), []int{1}
}

func (x *ServerMessage) GetPayload() isServerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerMessage) GetText() string {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Text); ok {
			return x.Text
		}
	}
	return ""
}

func (x *ServerMessage) GetAudioChunk() []byte {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_AudioChunk); ok {
			return x.AudioChunk
		}
	}
	return nil
}

func (x *ServerMessage) GetToolCall() string {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_ToolCall); ok {
			return x.ToolCall
		}
	}
	return ""
}

func (x *ServerMessage) GetSystemLog() string {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_SystemLog); ok {
			return x.SystemLog
		}
	}
	return ""
}

func (x *ServerMessage) GetSpeakText() string {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_SpeakText); ok {
			return x.SpeakText
		}
	}
	return ""
}

type isServerMessage_Payload interface {
	isServerMessage_Payload()
}

type ServerMessage_Text struct {
	Text string `protobuf:"bytes,1,opt,name=text,proto3,oneof"` // Agent response text
}

type ServerMessage_AudioChunk struct {
	AudioChunk []byte `protobuf:"bytes,2,opt,name=audio_chunk,json=audioChunk,proto3,oneof"` // TTS audio bytes (MP3/PCM) to play
}

type ServerMessage_ToolCall struct {
	ToolCall string `protobuf:"bytes,3,opt,name=tool_call,json=toolCall,proto3,oneof"` // Tool execution info (optional)
}

type ServerMessage_SystemLog struct {
	SystemLog string `protobuf:"bytes,4,opt,name=system_log,json=systemLog,proto3,oneof"` // System/Debug logs
}

type ServerMessage_SpeakText struct {
	SpeakText string `protobuf:"bytes,5,opt,name=speak_text,json=speakText,proto3,oneof"` // Text for client-side TTS
}

func (*ServerMessage_Text) isServerMessage_Payload() {}

func (*ServerMessage_AudioChunk) isServerMessage_Payload() {}

func (*ServerMessage_ToolCall) isServerMessage_Payload() {}

func (*ServerMessage_SystemLog) isServerMessage_Payload() {}

func (*ServerMessage_SpeakText) isServerMessage_Payload() {}

var File_pkg_api_liviva_proto protoreflect.FileDescriptor

const file_pkg_api_liviva_proto_rawDesc = "" +
	"\n" +
	"\x14pkg/api/liviva.proto\x12\x03api\"|\n" +
	"\rClientMessage\x12\x14\n" +
	"\x04text\x18\x01 \x01(\tH\x00R\x04text\x12!\n" +
	"\vaudio_chunk\x18\x02 \x01(\fH\x00R\n" +
	"audioChunk\x12'\n" +
	"\x0esystem_command\x18\x03 \x01(\tH\x00R\rsystemCommandB\t\n" +
	"\apayload\"\xb4\x01\n" +
	"\rServerMessage\x12\x14\n" +
	"\x04text\x18\x01 \x01(\tH\x00R\x04text\x12!\n" +
	"\vaudio_chunk\x18\x02 \x01(\fH\x00R\n" +
	"audioChunk\x12\x1d\n" +
	"\ttool_call\x18\x03 \x01(\tH\x00R\btoolCall\x12\x1f\n" +
	"\n" +
	"system_log\x18\x04 \x01(\tH\x00R\tsystemLog\x12\x1f\n" +
	"\n" +
	"speak_text\x18\x05 \x01(\tH\x00R\tspeakTextB\t\n" +
	"\apayload2J\n" +
	"\rLivivaService\x129\n" +
	"\vChatSession\x12\x12.api.ClientMessage\x1a\x12.api.ServerMessage(\x010\x01B Z\x1egithub.com/kalt/liviva/pkg/apib\x06proto3"

var (
	file_pkg_api_liviva_proto_rawDescOnce sync.Once
	file_pkg_api_liviva_proto_rawDescData []byte
)

func file_pkg_api_liviva_proto_rawDescGZIP() []byte {
	file_pkg_api_liviva_proto_rawDescOnce.Do(func() {
		file_pkg_api_liviva_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_api_liviva_proto_rawDesc), len(file_pkg_api_liviva_proto_rawDesc)))
	})
	return file_pkg_api_liviva_proto_rawDescData
}

var file_pkg_api_liviva_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_api_liviva_proto_goTypes = []any{
	(*ClientMessage)(nil), // 0: api.ClientMessage
	(*ServerMessage)(nil), // 1: api.ServerMessage
}
var file_pkg_api_liviva_proto_depIdxs = []int32{
	0, // 0: api.LivivaService.ChatSession:input_type -> api.ClientMessage
	1, // 1: api.LivivaService.ChatSession:output_type -> api.ServerMessage
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_api_liviva_proto_init() }
func file_pkg_api_liviva_proto_init() {
	if File_pkg_api_liviva_proto != nil {
		return
	}
	file_pkg_api_liviva_proto_msgTypes[0].OneofWrappers = []any{
		(*ClientMessage_Text)(nil),
		(*ClientMessage_AudioChunk)(nil),
		(*ClientMessage_SystemCommand)(nil),
	}
	file_pkg_api_liviva_proto_msgTypes[1].OneofWrappers = []any{
		(*ServerMessage_Text)(nil),
		(*ServerMessage_AudioChunk)(nil),
		(*ServerMessage_ToolCall)(nil),
		(*ServerMessage_SystemLog)(nil),
		(*ServerMessage_SpeakText)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_api_liviva_proto_rawDesc), len(file_pkg_api_liviva_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_api_liviva_proto_goTypes,
		DependencyIndexes: file_pkg_api_liviva_proto_depIdxs,
		MessageInfos:      file_pkg_api_liviva_proto_msgTypes,
	}.Build()
	File_pkg_api_liviva_proto = out.File
	file_pkg_api_liviva_proto_goTypes = nil
	file_pkg_api_liviva_proto_depIdxs = nil
}
