// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.1
// source: pkg/api/liviva.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LivivaService_ChatSession_FullMethodName = "/api.LivivaService/ChatSession"
)

// LivivaServiceClient is the client API for LivivaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LivivaServiceClient interface {
	// Bidirectional streaming for chat, audio, and commands
	ChatSession(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientMessage, ServerMessage], error)
}

type livivaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLivivaServiceClient(cc grpc.ClientConnInterface) LivivaServiceClient {
	return &livivaServiceClient{cc}
}

func (c *livivaServiceClient) ChatSession(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientMessage, ServerMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LivivaService_ServiceDesc.Streams[0], LivivaService_ChatSession_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClientMessage, ServerMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LivivaService_ChatSessionClient = grpc.BidiStreamingClient[ClientMessage, ServerMessage]

// LivivaServiceServer is the server API for LivivaService service.
// All implementations must embed UnimplementedLivivaServiceServer
// for forward compatibility.
type LivivaServiceServer interface {
	// Bidirectional streaming for chat, audio, and commands
	ChatSession(grpc.BidiStreamingServer[ClientMessage, ServerMessage]) error
	mustEmbedUnimplementedLivivaServiceServer()
}

// UnimplementedLivivaServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLivivaServiceServer struct{}

func (UnimplementedLivivaServiceServer) ChatSession(grpc.BidiStreamingServer[ClientMessage, ServerMessage]) error {
	return status.Error(codes.Unimplemented, "method ChatSession not implemented")
}
func (UnimplementedLivivaServiceServer) mustEmbedUnimplementedLivivaServiceServer() {}
func (UnimplementedLivivaServiceServer) testEmbeddedByValue()                       {}

// UnsafeLivivaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LivivaServiceServer will
// result in compilation errors.
type UnsafeLivivaServiceServer interface {
	mustEmbedUnimplementedLivivaServiceServer()
}

func RegisterLivivaServiceServer(s grpc.ServiceRegistrar, srv LivivaServiceServer) {
	// If the following call panics, it indicates UnimplementedLivivaServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LivivaService_ServiceDesc, srv)
}

func _LivivaService_ChatSession_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(LivivaServiceServer).ChatSession(&grpc.GenericServerStream[ClientMessage, ServerMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LivivaService_ChatSessionServer = grpc.BidiStreamingServer[ClientMessage, ServerMessage]

// LivivaService_ServiceDesc is the grpc.ServiceDesc for LivivaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LivivaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.LivivaService",
	HandlerType: (*LivivaServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ChatSession",
			Handler:       _LivivaService_ChatSession_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pkg/api/liviva.proto",
}
