// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: pkg/api/liviva.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ClientMessage_Text
	//	*ClientMessage_AudioChunk
	//	*ClientMessage_SystemCommand
	//	*ClientMessage_ToolResponse
	//	*ClientMessage_SaveArtifactRequest
	Payload       isClientMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	mi := &file_pkg_api_liviva_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_liviva_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_pkg_api_liviva_proto_rawDescGZIP(), []int{0}
}

func (x *ClientMessage) GetPayload() isClientMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ClientMessage) GetText() string {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_Text); ok {
			return x.Text
		}
	}
	return ""
}

func (x *ClientMessage) GetAudioChunk() []byte {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_AudioChunk); ok {
			return x.AudioChunk
		}
	}
	return nil
}

func (x *ClientMessage) GetSystemCommand() string {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_SystemCommand); ok {
			return x.SystemCommand
		}
	}
	return ""
}

func (x *ClientMessage) GetToolResponse() *ToolResponse {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_ToolResponse); ok {
			return x.ToolResponse
		}
	}
	return nil
}

func (x *ClientMessage) GetSaveArtifactRequest() *Artifact {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_SaveArtifactRequest); ok {
			return x.SaveArtifactRequest
		}
	}
	return nil
}

type isClientMessage_Payload interface {
	isClientMessage_Payload()
}

type ClientMessage_Text struct {
	Text string `protobuf:"bytes,1,opt,name=text,proto3,oneof"` // User typed text or transcribed speech
}

type ClientMessage_AudioChunk struct {
	AudioChunk []byte `protobuf:"bytes,2,opt,name=audio_chunk,json=audioChunk,proto3,oneof"` // Raw audio bytes (PCM) from microphone
}

type ClientMessage_SystemCommand struct {
	SystemCommand string `protobuf:"bytes,3,opt,name=system_command,json=systemCommand,proto3,oneof"` // e.g. "/voice on", "/shutdown"
}

type ClientMessage_ToolResponse struct {
	ToolResponse *ToolResponse `protobuf:"bytes,4,opt,name=tool_response,json=toolResponse,proto3,oneof"` // Output from a client-side tool
}

type ClientMessage_SaveArtifactRequest struct {
	SaveArtifactRequest *Artifact `protobuf:"bytes,5,opt,name=save_artifact_request,json=saveArtifactRequest,proto3,oneof"` // Upload a file from client to server
}

func (*ClientMessage_Text) isClientMessage_Payload() {}

func (*ClientMessage_AudioChunk) isClientMessage_Payload() {}

func (*ClientMessage_SystemCommand) isClientMessage_Payload() {}

func (*ClientMessage_ToolResponse) isClientMessage_Payload() {}

func (*ClientMessage_SaveArtifactRequest) isClientMessage_Payload() {}

type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerMessage_Text
	//	*ServerMessage_AudioChunk
	//	*ServerMessage_ToolCall
	//	*ServerMessage_SystemLog
	//	*ServerMessage_SpeakText
	//	*ServerMessage_ToolRequest
	//	*ServerMessage_Artifact
	//	*ServerMessage_Metrics
	Payload       isServerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_pkg_api_liviva_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_liviva_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_pkg_api_liviva_proto_rawDescGZIP(), []int{1}
}

func (x *ServerMessage) GetPayload() isServerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerMessage) GetText() string {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Text); ok {
			return x.Text
		}
	}
	return ""
}

func (x *ServerMessage) GetAudioChunk() []byte {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_AudioChunk); ok {
			return x.AudioChunk
		}
	}
	return nil
}

func (x *ServerMessage) GetToolCall() string {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_ToolCall); ok {
			return x.ToolCall
		}
	}
	return ""
}

func (x *ServerMessage) GetSystemLog() string {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_SystemLog); ok {
			return x.SystemLog
		}
	}
	return ""
}

func (x *ServerMessage) GetSpeakText() string {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_SpeakText); ok {
			return x.SpeakText
		}
	}
	return ""
}

func (x *ServerMessage) GetToolRequest() *ToolRequest {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_ToolRequest); ok {
			return x.ToolRequest
		}
	}
	return nil
}

func (x *ServerMessage) GetArtifact() *Artifact {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Artifact); ok {
			return x.Artifact
		}
	}
	return nil
}

func (x *ServerMessage) GetMetrics() *Metrics {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Metrics); ok {
			return x.Metrics
		}
	}
	return nil
}

type isServerMessage_Payload interface {
	isServerMessage_Payload()
}

type ServerMessage_Text struct {
	Text string `protobuf:"bytes,1,opt,name=text,proto3,oneof"` // Agent response text
}

type ServerMessage_AudioChunk struct {
	AudioChunk []byte `protobuf:"bytes,2,opt,name=audio_chunk,json=audioChunk,proto3,oneof"` // TTS audio bytes (MP3/PCM) to play
}

type ServerMessage_ToolCall struct {
	ToolCall string `protobuf:"bytes,3,opt,name=tool_call,json=toolCall,proto3,oneof"` // Legacy tool info (keep for backward compat if needed)
}

type ServerMessage_SystemLog struct {
	SystemLog string `protobuf:"bytes,4,opt,name=system_log,json=systemLog,proto3,oneof"` // System/Debug logs
}

type ServerMessage_SpeakText struct {
	SpeakText string `protobuf:"bytes,5,opt,name=speak_text,json=speakText,proto3,oneof"` // Text for client-side TTS
}

type ServerMessage_ToolRequest struct {
	ToolRequest *ToolRequest `protobuf:"bytes,6,opt,name=tool_request,json=toolRequest,proto3,oneof"` // Request to execute a tool on the client
}

type ServerMessage_Artifact struct {
	Artifact *Artifact `protobuf:"bytes,7,opt,name=artifact,proto3,oneof"` // Download/Stream an artifact to the client
}

type ServerMessage_Metrics struct {
	Metrics *Metrics `protobuf:"bytes,8,opt,name=metrics,proto3,oneof"` // Model usage and context stats
}

func (*ServerMessage_Text) isServerMessage_Payload() {}

func (*ServerMessage_AudioChunk) isServerMessage_Payload() {}

func (*ServerMessage_ToolCall) isServerMessage_Payload() {}

func (*ServerMessage_SystemLog) isServerMessage_Payload() {}

func (*ServerMessage_SpeakText) isServerMessage_Payload() {}

func (*ServerMessage_ToolRequest) isServerMessage_Payload() {}

func (*ServerMessage_Artifact) isServerMessage_Payload() {}

func (*ServerMessage_Metrics) isServerMessage_Payload() {}

type ToolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                            // Correlation ID
	ToolName      string                 `protobuf:"bytes,2,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`                // e.g. "system.exec"
	ArgumentsJson string                 `protobuf:"bytes,3,opt,name=arguments_json,json=argumentsJson,proto3" json:"arguments_json,omitempty"` // JSON arguments for the tool
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolRequest) Reset() {
	*x = ToolRequest{}
	mi := &file_pkg_api_liviva_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolRequest) ProtoMessage() {}

func (x *ToolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_liviva_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolRequest.ProtoReflect.Descriptor instead.
func (*ToolRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_liviva_proto_rawDescGZIP(), []int{2}
}

func (x *ToolRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ToolRequest) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ToolRequest) GetArgumentsJson() string {
	if x != nil {
		return x.ArgumentsJson
	}
	return ""
}

type ToolResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`         // Correlation ID
	Output        string                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"` // Tool output (text/json)
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`   // Error message if any
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolResponse) Reset() {
	*x = ToolResponse{}
	mi := &file_pkg_api_liviva_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolResponse) ProtoMessage() {}

func (x *ToolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_liviva_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolResponse.ProtoReflect.Descriptor instead.
func (*ToolResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_liviva_proto_rawDescGZIP(), []int{3}
}

func (x *ToolResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ToolResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *ToolResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Artifact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	MimeType      string                 `protobuf:"bytes,3,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	Version       int32                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Artifact) Reset() {
	*x = Artifact{}
	mi := &file_pkg_api_liviva_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Artifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Artifact) ProtoMessage() {}

func (x *Artifact) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_liviva_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Artifact.ProtoReflect.Descriptor instead.
func (*Artifact) Descriptor() ([]byte, []int) {
	return file_pkg_api_liviva_proto_rawDescGZIP(), []int{4}
}

func (x *Artifact) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *Artifact) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Artifact) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *Artifact) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type SaveArtifactResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Version       int32                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveArtifactResponse) Reset() {
	*x = SaveArtifactResponse{}
	mi := &file_pkg_api_liviva_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveArtifactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveArtifactResponse) ProtoMessage() {}

func (x *SaveArtifactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_liviva_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveArtifactResponse.ProtoReflect.Descriptor instead.
func (*SaveArtifactResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_liviva_proto_rawDescGZIP(), []int{5}
}

func (x *SaveArtifactResponse) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *SaveArtifactResponse) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *SaveArtifactResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Metrics struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PromptTokens      int32                  `protobuf:"varint,1,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	CompletionTokens  int32                  `protobuf:"varint,2,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"`
	TotalTokens       int32                  `protobuf:"varint,3,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	ContextPercentage int32                  `protobuf:"varint,4,opt,name=context_percentage,json=contextPercentage,proto3" json:"context_percentage,omitempty"` // Percentage of context window used
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Metrics) Reset() {
	*x = Metrics{}
	mi := &file_pkg_api_liviva_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metrics) ProtoMessage() {}

func (x *Metrics) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_liviva_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metrics.ProtoReflect.Descriptor instead.
func (*Metrics) Descriptor() ([]byte, []int) {
	return file_pkg_api_liviva_proto_rawDescGZIP(), []int{6}
}

func (x *Metrics) GetPromptTokens() int32 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *Metrics) GetCompletionTokens() int32 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

func (x *Metrics) GetTotalTokens() int32 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

func (x *Metrics) GetContextPercentage() int32 {
	if x != nil {
		return x.ContextPercentage
	}
	return 0
}

var File_pkg_api_liviva_proto protoreflect.FileDescriptor

const file_pkg_api_liviva_proto_rawDesc = "" +
	"\n" +
	"\x14pkg/api/liviva.proto\x12\x03api\"\xfb\x01\n" +
	"\rClientMessage\x12\x14\n" +
	"\x04text\x18\x01 \x01(\tH\x00R\x04text\x12!\n" +
	"\vaudio_chunk\x18\x02 \x01(\fH\x00R\n" +
	"audioChunk\x12'\n" +
	"\x0esystem_command\x18\x03 \x01(\tH\x00R\rsystemCommand\x128\n" +
	"\rtool_response\x18\x04 \x01(\v2\x11.api.ToolResponseH\x00R\ftoolResponse\x12C\n" +
	"\x15save_artifact_request\x18\x05 \x01(\v2\r.api.ArtifactH\x00R\x13saveArtifactRequestB\t\n" +
	"\apayload\"\xc2\x02\n" +
	"\rServerMessage\x12\x14\n" +
	"\x04text\x18\x01 \x01(\tH\x00R\x04text\x12!\n" +
	"\vaudio_chunk\x18\x02 \x01(\fH\x00R\n" +
	"audioChunk\x12\x1d\n" +
	"\ttool_call\x18\x03 \x01(\tH\x00R\btoolCall\x12\x1f\n" +
	"\n" +
	"system_log\x18\x04 \x01(\tH\x00R\tsystemLog\x12\x1f\n" +
	"\n" +
	"speak_text\x18\x05 \x01(\tH\x00R\tspeakText\x125\n" +
	"\ftool_request\x18\x06 \x01(\v2\x10.api.ToolRequestH\x00R\vtoolRequest\x12+\n" +
	"\bartifact\x18\a \x01(\v2\r.api.ArtifactH\x00R\bartifact\x12(\n" +
	"\ametrics\x18\b \x01(\v2\f.api.MetricsH\x00R\ametricsB\t\n" +
	"\apayload\"a\n" +
	"\vToolRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttool_name\x18\x02 \x01(\tR\btoolName\x12%\n" +
	"\x0earguments_json\x18\x03 \x01(\tR\rargumentsJson\"L\n" +
	"\fToolResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06output\x18\x02 \x01(\tR\x06output\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"q\n" +
	"\bArtifact\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x1b\n" +
	"\tmime_type\x18\x03 \x01(\tR\bmimeType\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x05R\aversion\"b\n" +
	"\x14SaveArtifactResponse\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\xad\x01\n" +
	"\aMetrics\x12#\n" +
	"\rprompt_tokens\x18\x01 \x01(\x05R\fpromptTokens\x12+\n" +
	"\x11completion_tokens\x18\x02 \x01(\x05R\x10completionTokens\x12!\n" +
	"\ftotal_tokens\x18\x03 \x01(\x05R\vtotalTokens\x12-\n" +
	"\x12context_percentage\x18\x04 \x01(\x05R\x11contextPercentage2J\n" +
	"\rLivivaService\x129\n" +
	"\vChatSession\x12\x12.api.ClientMessage\x1a\x12.api.ServerMessage(\x010\x01B Z\x1egithub.com/kalt/liviva/pkg/apib\x06proto3"

var (
	file_pkg_api_liviva_proto_rawDescOnce sync.Once
	file_pkg_api_liviva_proto_rawDescData []byte
)

func file_pkg_api_liviva_proto_rawDescGZIP() []byte {
	file_pkg_api_liviva_proto_rawDescOnce.Do(func() {
		file_pkg_api_liviva_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_api_liviva_proto_rawDesc), len(file_pkg_api_liviva_proto_rawDesc)))
	})
	return file_pkg_api_liviva_proto_rawDescData
}

var file_pkg_api_liviva_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pkg_api_liviva_proto_goTypes = []any{
	(*ClientMessage)(nil),        // 0: api.ClientMessage
	(*ServerMessage)(nil),        // 1: api.ServerMessage
	(*ToolRequest)(nil),          // 2: api.ToolRequest
	(*ToolResponse)(nil),         // 3: api.ToolResponse
	(*Artifact)(nil),             // 4: api.Artifact
	(*SaveArtifactResponse)(nil), // 5: api.SaveArtifactResponse
	(*Metrics)(nil),              // 6: api.Metrics
}
var file_pkg_api_liviva_proto_depIdxs = []int32{
	3, // 0: api.ClientMessage.tool_response:type_name -> api.ToolResponse
	4, // 1: api.ClientMessage.save_artifact_request:type_name -> api.Artifact
	2, // 2: api.ServerMessage.tool_request:type_name -> api.ToolRequest
	4, // 3: api.ServerMessage.artifact:type_name -> api.Artifact
	6, // 4: api.ServerMessage.metrics:type_name -> api.Metrics
	0, // 5: api.LivivaService.ChatSession:input_type -> api.ClientMessage
	1, // 6: api.LivivaService.ChatSession:output_type -> api.ServerMessage
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_pkg_api_liviva_proto_init() }
func file_pkg_api_liviva_proto_init() {
	if File_pkg_api_liviva_proto != nil {
		return
	}
	file_pkg_api_liviva_proto_msgTypes[0].OneofWrappers = []any{
		(*ClientMessage_Text)(nil),
		(*ClientMessage_AudioChunk)(nil),
		(*ClientMessage_SystemCommand)(nil),
		(*ClientMessage_ToolResponse)(nil),
		(*ClientMessage_SaveArtifactRequest)(nil),
	}
	file_pkg_api_liviva_proto_msgTypes[1].OneofWrappers = []any{
		(*ServerMessage_Text)(nil),
		(*ServerMessage_AudioChunk)(nil),
		(*ServerMessage_ToolCall)(nil),
		(*ServerMessage_SystemLog)(nil),
		(*ServerMessage_SpeakText)(nil),
		(*ServerMessage_ToolRequest)(nil),
		(*ServerMessage_Artifact)(nil),
		(*ServerMessage_Metrics)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_api_liviva_proto_rawDesc), len(file_pkg_api_liviva_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_api_liviva_proto_goTypes,
		DependencyIndexes: file_pkg_api_liviva_proto_depIdxs,
		MessageInfos:      file_pkg_api_liviva_proto_msgTypes,
	}.Build()
	File_pkg_api_liviva_proto = out.File
	file_pkg_api_liviva_proto_goTypes = nil
	file_pkg_api_liviva_proto_depIdxs = nil
}
